[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"

# Security headers and redirects
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://script.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://script.google.com; frame-ancestors 'none'"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security redirects
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/package.json"
  to = "/404"
  status = 404

[[redirects]]
  from = "/package-lock.json"
  to = "/404"
  status = 404
